### ISSUE TITLE
API Documentation - Lightning talk

### ISSUE THREAD

**Issue by lrepolho** [sydphp/meetup-talks#42]
If there are still slots available I would like to do a quick overview of tools I've been using with my team to generate useful and updated documentation for our microservices, everything commited in the repos instead of using softwares such as Confluence or Google Drive docs.

I'm available to speak next Thursday 28th of Feb.

Tags: documentation, api, documentation as code, apidocs, swagger, postman, confluence

**Comment by Szasza** [comment]
Great, thank you @lrepolho for volunteering as a speakr, it is much appreciated.

Your lightning talk slot would be 8:15-8:20pm, will add your talk to the meetup page shortly.

**Comment by Szasza** [comment]
@lrepolho I had the short talk about the API documentation due to your absence, please don't hesitate if there is any other topic that you would be keen to hear about.

**Comment by Szasza** [comment]
Presented in February 2019
