### ISSUE TITLE
Getting to grips with PHP on Kubernetes

### ISSUE THREAD

**Issue by Szasza** [sydphp/meetup-talks#43]
#### Description

"PHP applications can be deployed in many ways - copied to one or more servers to run directly on the given OS, packaged into a container, upladed to AWS Lambda to run in a roundabout way, and so on. One of the options is using a Kubernetes cluster, which also provides many other services readily available. Let's see how a Kubernetes-based PHP API orchestration works in practice!"

**Comment by Szasza** [comment]
Presented in February 2019

Slides: https://drive.google.com/file/d/1QTguSmERuUhaVV1trja00AqU7sViR1jD/view?usp=sharing

Video: https://www.youtube.com/watch?v=xp_29dkKayE

**Comment by adrianspacely** [comment]
Thank you for sharing this 😁

**Comment by Szasza** [comment]
Sure thing @adrianb93 :grin:
