### ISSUE TITLE
Application Localisation

### ISSUE THREAD

**Issue by salarmehr** [sydphp/meetup-talks#44]
I'm keen to have a walkthrough on Application Localisation using the intl extension if possible on the next meetup.  It would be a long talk.

**Comment by Szasza** [comment]
Hi @salarmehr,

Thank you for volunteering.

Just to clarify:
- Would this be a lightning talk or a long talk?
- If it is a lightning talk, would you be ok having it in February or would you rather have it in March?

Thank you in advance.

**Comment by salarmehr** [comment]
Hi Szasza,
It would be a long talk and if possible for the February's meetup, please.

**Comment by Szasza** [comment]
Hi @salarmehr,

Awesome, a long talk is always welcomed.

Regarding the time, February's meetup already has the two long talks. Would it be ok for you to have yours in March, or are there any circumstances (i.e. being abroad) which would cause an issue?

Thank you again.

**Comment by Szasza** [comment]
Hi @salarmehr,

We just had a chat with @dkcwd and he is happy to have his talk in March if you are still keen to do it in February.

Could you please confirm if you are still ok for February?

Thank you in advance.

**Comment by salarmehr** [comment]
Hi @Szasza,

Thanks. Yes, February works for me. So if %100 definite I will start working on the power point slide. 

Regards,
Reza

**Comment by Szasza** [comment]
Hi @salarmehr ,

Great, thank you both for the quick response and for the presentation, I can confirm that it is 100% that you will get the 30-min slot.

The only other thing I would like to ask is that could you please send me a 2-3 sentence intro text for your presentation that can be put on the meetup page? Please feel free to take a look at current/previous meetup pages to see how they look like.

It doesn't need to be long, just a quick summary of what the talk is about.

Thank you in advance, it is much appreciated.

**Comment by salarmehr** [comment]
### Make your application locale-aware :: Reza Salarmher

Do you want to attract visitors from China or Brazil? But to make them take your applicaiton seriously, you have to internationalise your web application. You need to render dates, numbers and currencies in the format that is familiar for your new audience. PHP has built-in support for this task similar to most other programming languages. After this talk, we will learn how to globalise our web app smoothly using ICU (Intl) library.

**Comment by Szasza** [comment]
@salarmehr Awesome, thank you, I will update the meetup page shortly and send out a notification to the community about the change of schedule.

**Comment by Szasza** [comment]
Presented in February 2019

Slides: https://drive.google.com/file/d/1P7rh30OYGVVo6ZekNLyAGuEm9CTeGTc9/view?usp=sharing

Video: https://www.youtube.com/watch?v=YJREXnOD1MI
