### ISSUE TITLE
Living with the Legacy

### ISSUE THREAD

**Issue by dave-newson** [sydphp/meetup-talks#46]
*Description*

Every time we build something, we learn and improve our methods, however anything we've built in the past can be difficult to improve, modify or even trust.  How can we take old scary code, and make it something we can be proud of?

**Comment by Szasza** [comment]
Thank you @dave-newson , much appreciated.

**Comment by dave-newson** [comment]
Presentation PDF and code examples: https://github.com/dave-newson/preso-living-with-the-legacy

**Comment by Szasza** [comment]
The YouTube video can be found at https://www.youtube.com/watch?v=wNIFr7XF-9c

@dave-newson thank you again for the talk!
