### ISSUE TITLE
Dependency inversion, injection and the containers

### ISSUE THREAD

**Issue by luads** [sydphp/meetup-talks#48]
In this talk, I'll talk about the dependency inversion principle, dependency injection and DI containers, using real-life examples for each of the concepts to understand the difference between them, how they align together and the benefits of applying it to your code.

The talk goes back to some base concepts and ties them together while showing practical PHP examples. It takes about 30 minutes.

**Comment by Szasza** [comment]
Thank you @luads , much appreciated, I will add it to the event page.

**Comment by Szasza** [comment]
The slides can be found here: https://speakerdeck.com/luads/dependency-inversion-injection-and-the-containers

**Comment by Szasza** [comment]
YouTube link: https://www.youtube.com/watch?v=V4CXvKIiY7Y
