### ISSUE TITLE
Wordpress and the Modern PHP Developer, or How I made my peace with the most popular PHP application in the world

### ISSUE THREAD

**Issue by bluehaoran** [sydphp/meetup-talks#49]
Wordpress. Every user loves it, but every developer hates it. In this we walk through several production-ready libraries and tools you can use to modernise your Wordpress stack and find some semblance of sanity.

**Comment by Szasza** [comment]
Thank you @bluehaoran , it is much appreciated.

**Comment by Szasza** [comment]
Slides: https://docs.google.com/presentation/d/1XQlTwaFfUQrT-iZShoP9j1QlTE3p9Ox0F4YOAkBG1kE/edit?usp=sharing

Medium post: https://medium.com/@thehaoran/modernising-your-wordpress-stack-or-the-modern-php-developer-and-wordpress-afd52f1f5a1

**Comment by Szasza** [comment]
YouTube link: https://www.youtube.com/watch?v=Eegk50PPy4E
