### ISSUE TITLE
Enterprise API with API-Platform.com

### ISSUE THREAD

**Issue by farazive** [sydphp/meetup-talks#50]
In this talk, we will go through the amazing [API Platform](https://api-platform.com/) that has taken the Symfony world by storm. We will go through best practices and also discuss some global standards for your API.

**Comment by Szasza** [comment]
Thank you for the talk in advance @farazive , much appreciated!

**Comment by farazive** [comment]
Thank you for the opportunity @Szasza Excited to have you back at ELMO :)

**Comment by Szasza** [comment]
YouTube link: https://www.youtube.com/watch?v=UAzopaQf5uE
