### ISSUE TITLE
End-to-end tests with CypressJS

### ISSUE THREAD

**Issue by grenoult** [sydphp/meetup-talks#51]

**Comment by grenoult** [comment]
In this lighting talk, we will talk about how to test your application with CypressJS.
Although CypressJS is a JS tool, your PHP application has a frontend that the end user will interact with.

**Comment by Szasza** [comment]
Thank you for the talk and the details @grenoult , much appreciated!

**Comment by Szasza** [comment]
YouTube link: https://www.youtube.com/watch?v=V9KBT_H1kpk
