### ISSUE TITLE
RabbitMQ + PHP

### ISSUE THREAD

**Issue by theAttenzione** [sydphp/meetup-talks#52]
**Time:** 30-40 min
**Description:** on this  workshop we will try to do the following:
- Walk through the main AMQP 0.9.1 protocol principles
- Explore RabbitMQ Manager web interface
- See how to use Rabbit in PHP
- Run a PHP consumer and produce some messages to it
- Ack and Reject messages
- Learn how Dead Letter Queue works

**Comment by Szasza** [comment]
Thank you for the talk in advance @theAttenzione , it is much appreciated!

**Comment by theAttenzione** [comment]
https://github.com/php-amqplib/php-amqplib - low level
https://github.com/php-amqplib/RabbitMqBundle - high level

**Comment by Szasza** [comment]
YouTube link: https://www.youtube.com/watch?v=AAsJGYZe7ZE
