### ISSUE TITLE
Doctrine Entity Manager: handling transactions properly [lightning talk]

### ISSUE THREAD

**Issue by theAttenzione** [sydphp/meetup-talks#54]
In this lightning talk, we'll speak of how to use the power of Entity Manager. We'll focus on:
- What is the Unit Of Work pattern, and how it is used in the Entity Manager
- How we can use its power to get rid of begin/commit transaction blocks in our PHP code
- How we can use its power to reduce the number of Repositories our classes depend on

**Duration**: 5-7 mins

**Comment by nootanghimire** [comment]
Closing to de-clutter main issue view
