### ISSUE TITLE
Working on old code is a privilege not a punishment

### ISSUE THREAD

**Issue by declaneugeneleekennedy** [sydphp/meetup-talks#55]
PHP is a relatively young language, which began as the personal project of the creator and now powers over 80% of the web. As a result, it has changed massively over the past 25 years, and a lot of techniques and practices which were considered to be idiomatic 10 years ago are now looked at like they're a mysterious stain on your carpet.

This talk is all about the things you can learn by exploring battle-tested production code, if you stop treating maintaining classic code as a punishment.

**Duration:** 20-30 minutes

**Comment by Szasza** [comment]
Hi @declaneugeneleekennedy ,

Thank you for volunteering to talk, it is greatly appreciated.

Looking forward to it!

**Comment by Szasza** [comment]
YouTube link: https://www.youtube.com/watch?v=oDlKu28w-Ik
