### ISSUE TITLE
My Quest for Test Doubles in Unit Testing

### ISSUE THREAD

**Issue by mith495** [sydphp/meetup-talks#56]
This talk is about my quest for Test Doubles in PHP ecosystem. This would be a lightning talk.

I will be covering the following topics:
- My Context/motivation and misconceptions
- Types of test doubles
- Some golden rules about test doubles
- Gotcha/Considerations

**Duration**: 15~ mins

**Comment by Szasza** [comment]
Great, thank you @mith495 , looking forward to the talk at the end of the month!

**Comment by Szasza** [comment]
Hi @mith495 ,

Thank you again for the talk, it is much appreciated. May I ask you to please share a link to your presentation so I can finalise the video footage?

Thank you for your help.

**Comment by mith495** [comment]
Hi @Szasza,
Here is the link for my slides:
https://docs.google.com/presentation/d/1Jy-axHu1RZDQS7YgHySDFaRhNRLzSCBezYBUTykn8_g/edit?usp=sharing

Thanks,
Mith

**Comment by Szasza** [comment]
Hi @mith495 ,

Great, thank you!
