### ISSUE TITLE
Xdebug tips and tricks

### ISSUE THREAD

**Issue by beerbrewing** [sydphp/meetup-talks#57]
Kev Lambert (Pyrmont Brewery / SwitchMedia) is happy to explain how PHP debugging works, how to set up local and remote debug and other useful related stuff (short lightning preso)
[@kevleyski](https://linkedin.com/in/kevleyski) [pyrmontbrewery.com](https://pyrmontbrewery.com)

**Comment by beerbrewing** [comment]
Kev Lambert is happy to explain how PHP debugging works, how to set up local and remote debug and other useful related stuff (short lightning preso)

**Comment by Szasza** [comment]
Thank you @beerbrewing for the topic, much appreciated.

Looking forward to it already :)
