### ISSUE TITLE
Create videos using PHP and the Shotstack API

### ISSUE THREAD

**Issue by jeffski** [sydphp/meetup-talks#58]
I would like to do a short talk and demo of how to create, edit and personalise videos at scale using PHP and the Shotstack cloud video editing API: https://shotstack.io/

Talk could cover:
- Brief intro about Shotstack platform and early stage startup
- How to create an edit (JSON)
- How to create an edit using SDK (composer package) and PHP
- Hello World live demo
- Q&A

Could present in 15 min format or 30 min format.

**Comment by Szasza** [comment]
Hi @jeffski ,

Thank you for submitting the talk topic, it is greatly appreciated, the topic sounds really interesting!

If that works for you, I would like to add your talk to our November meetup, which is planned to be a series of lightning talks so for that the 15min format would be better.

Looking forward to your feedback on the feasibility of the above, and thank you again!

**Comment by jeffski** [comment]
Hi @Szasza - sounds good, count me in.

**Comment by Szasza** [comment]
@jeffski great, thank you for the quick confirmation and again for the talk, looking forward to it!

Please don't hesitate to reach out if there are any questions.
